development:
   adapter: mysql
   database: RendezWho
   username: root
   password: swatkat
   host: localhost
   port: 3306
production:
   adapter: mysql
   database: RendezWho
   username: root
   password: swatkat
   host: localhost
   port: 3306

